// routes/dataRoutes.js
const express = require("express");
const dataController = require("../controllers/dataController");
const router = express.Router();

const multer = require('multer');
const upload = multer({
    storage: multer.memoryStorage(),
    limits: { fileSize: 50 * 1024 * 1024 }, // 50MB limit
  });

router.post("/login", dataController.login);
router.post("/forgetPassword", dataController.forgetPassword);
router.post('/verify-otp', dataController.verifyOtp);
router.post("/signup", dataController.signUp);
router.post("/city", dataController.getCity)
router.post("/variant", dataController.getvariant)
router.post("/uom", dataController.getuom)
router.post("/country", dataController.getCountry)
router.post("/state", dataController.getState)
router.post("/status", dataController.getStatus)
router.post("/Shift", dataController.getShift)
router.post("/Transaction", dataController.getTransaction)
router.post("/gender", dataController.getGender)
router.post("/getTaxApplicable", dataController.getTaxApplicable)
router.post("/Loginorout", dataController.getLoginorout)
router.get("/", dataController.getAllData)
router.post("/add", upload.fields([
  { name: 'company_logo', maxCount: 1 },
  { name: 'authorisedSignatur', maxCount: 1 }
]),dataController.addData)
router.post("/useradd",upload.single('user_img'),dataController.userAddData)
router.get ("/userData", dataController.getAlluserData)
router.get("/WareHouseData",dataController.getAllWareHouseData)
router.get("/RoleInfoData", dataController.getAllRoleInfoData)
router.post("/addRoleInfoData", dataController.AddRoleInfoData)
router.post("/Roleupdate", dataController.RolesaveEditedData)
router.post("/saveEditedData", dataController.saveEditedData);
router.post("/delete", dataController.deleteData);
router.post("/userdelete", dataController.UserdeleteData)
router.post("/userupdate", dataController.UsersaveEditedData)
router.get("/attrihdrdata",dataController.getAllattributehdrData)
router.post("/addattriData",dataController.addattrihdrData)
//router.post("/updattriData",dataController.updattrihdrData)
router.get("/attributedetData",dataController.getAllattributedetData)
router.post("/addattridetData",dataController.addattridetData)
router.post("/updattridetData",dataController.updattridetData)
router.post("/delattridetData",dataController.deleteAttriDetailData)
router.get("/hdrcode", dataController.gethdrcode)
router.post("/delPer", dataController.getDeletepermission)
router.post("/regbrand", dataController.getregisterbrand)
router.post("/ourbrand", dataController.getourbrand)
router.post("/companysearchcriteria",dataController.getsearchdata)
router.post("/addCompanyMappingData",dataController.addCompanyMappingData)
router.get("/CompanyMappingData",dataController.getAllCompanyMappingData)
router.get("/usercode",dataController.getUsercode)
router.post("/Usertype", dataController.getUsertype)
router.get("/Companyno",dataController.getCompanyno)
router.get("/locationno",dataController.getLocationno)
router.post("/paytype", dataController.getPaytype)
router.post("/purchasetype", dataController.getPurchasetype)
router.post("/salestype", dataController.getSalestype)
router.post("/ordertype", dataController.getordertype)
router.post("/roleid", dataController.getroleid)
router.get("/UserRoleMappingData",dataController.getAllUserRoleMappingData)
router.post("/addUserRoleMappingData",dataController.addUserRoleMappingData)
router.post("/locationSearchdata",dataController.getlocationsearchdata)
router.post("/addlocationinfo",dataController.addlocationinfo)
router.post("/location_no",dataController.locationsaveEditedData)
router.post("/deletelocation",dataController.locationdeleteData)
router.post("/userrolsearchdata",dataController.getUserrolesearchdata)
router.post("/usersearchcriteria",dataController.getUsersearchdata)
router.post("/Rolesearchdata",dataController.getRolesearchdata)
router.post("/roledelete",dataController.roledeleteData)
router.post("/companymappingsearchdata",dataController.getcompanymappingsearchdata)
router.post("/attributeSearchdata",dataController.getattributeSearchdata)
router.post("/transactiontype",dataController.gettranstype)
router.post("/screentype",dataController.getscreentype)
router.post("/Passwords",dataController.Passwords)
router.post("/getusercompany",dataController.getusercompany)
router.post("/updcompanymapping",dataController.updcompanymapping)
router.post("/commappingdeleteData",dataController.commappingdeleteData)
router.post("/Screens",dataController.getScreens)
router.post("/Permissions",dataController.getPermissions)
router.post("/facereg", dataController.facereg);
router.post("/getItem",dataController.getItem) 
router.post("/RollMappingDelete",dataController.RollMappingDelete)
router.post("/updateRoleMapping",dataController.updateRoleMapping)
router.post("/UserRole",dataController.getUserRole)
router.post("/UpdateUserImage",upload.single('user_img'),dataController.UpdateUserImage)
router.post("/getInventoryTransaction",dataController.getInventoryTransaction)
router.post("/getEmptype", dataController.getEmptype)
router.post("/Condition", dataController.getCondition)
router.post("/LocationUpdate", dataController.LocationUpdate)
router.post("/CompanyUpdate",upload.fields([
  { name: 'company_logo', maxCount: 1 },
  { name: 'authorisedSignatur', maxCount: 1 }
]),dataController.CompanyUpdate)
router.post("/UpdateCompanyImage",upload.single('company_logo'),dataController.UpdateCompanyImage)
router.post("/RoleUpdates", dataController.RoleUpdate)
router.post("/UserUpdates", upload.single('user_images'), dataController.UserUpdate)
router.post("/CompanyMappingUpdate", dataController.CompanyMappingUpdate)
router.post("/RoleMappingUpdate", dataController.RoleMappingUpdate)
router.post("/AttributeUpdate", dataController.AttributeUpdate)
router.post("/getEvent", dataController.getEvent)
router.post("/getsiblings",dataController.getsiblings)
router.post("/getKids",dataController.getkids)
router.post("/getMartial",dataController.getMartial)
router.post("/getSalaryType",dataController.getSalaryType)
router.post("/getPayscale",dataController.getPayscale)
router.post("/getLoanID",dataController.getLoanID)
router.post("/getDocumentType",dataController.getDocumentType)
router.post("/getrelation",dataController. getrelation)
router.post("/getannoncementtype",dataController. getannoncementtype)
router.post("/getAnnouncementDetail",dataController. getAnnouncementDetail)
router.post("/getAnnouncement_Msg",dataController. getAnnouncement_Msg)
router.get("/getAnnouncementDetail",dataController.getAnnouncement)
router.post("/getcompanyshift",dataController.getcompanyshift)
router.post("/getOverallTAX",dataController.getOverallTAX)
router.post("/getInvocieType",dataController.getInvocieType)
router.post("/Terms",dataController.TermsDC)
router.post("/TermsQO",dataController.TermsQO)
router.post("/TermsPO",dataController.TermsPO)
router.post("/TermsTI",dataController.TermsTI)
router.post("/getLeaveType",dataController.getLeaveType)
router.post("/getSelectSlot",dataController.getSelectSlot)
router.post("/getDashBoardType",dataController.getDashBoardType)
router.post("/getGSTReport",dataController.getGSTReport)
router.post("/getType",dataController.getType)
router.post("/getAccrual",dataController.getAccrual)
router.post("/getExceedLeave",dataController.getExceedLeave)
router.post("/getLeaveReason",dataController.getLeaveReason)
router.post("/getAnnouncement",dataController.getAnnouncement)
router.post("/getPendingStatus",dataController.getPendingStatus)
router.post("/getdefCustomer",dataController.getdefCustomer)
router.post("/getSalesMode",dataController.getSalesMode)
router.post("/getPurchaseAnalysis",dataController.getPurchaseAnalysis)
router.post("/getTaskstatus",dataController.getTaskstatus)
router.post("/PendingCustomer",dataController.PendingCustomer)
router.post("/getPriority",dataController.getPriority)
router.post("/Userdropdown",dataController.Userdropdown)
router.post("/getAnnouncementDuration",dataController.getAnnouncementDuration)
router.post("/getboolean", dataController.getboolean)
router.post("/savePdf", upload.single("pdf"), dataController.savePDFToPath);
router.post("/sendPayslipEmails", dataController.sendPayslipEmails)
router.post("/getDocument",dataController.getDocument)
router.post("/sendAutoMail",dataController.sendAutoMail)
router.post("/termsandCondition",dataController.termsandCondition)
router.post("/getLockType", dataController.getLockType)
router.post("/getPrint",dataController.getPrint)
router.post("/getcopies",dataController.getcopies)
router.post("/WeekOff",dataController.WeekOff)
router.post("/GenerateEmployee",dataController.GenerateEmployee)
router.post("/getLeaveStatus",dataController.getLeaveStatus)
router.post("/PatientMasterInsert", dataController.PatientMasterInsert)
router.post("/PatientMasterUpdate", dataController.PatientMasterUpdate)
router.post("/PatientMasterDelete", dataController.PatientMasterDelete)
router.post("/DoctorMasterInsert", dataController.HMS_DoctorMasterInsert)
router.post("/DoctorMasterUpdate", dataController.HMS_DoctorMasterUpdate)
router.post("/DoctorMasterDelete", dataController.HMS_DoctorMasterDelete)
router.post("/ClientMasterInsert", dataController.HMS_ClientMasterInsert)
router.post("/ClientMasterUpdate", dataController.HMS_ClientMasterUpdate)
router.post("/ClientMasterDelete", dataController.HMS_ClientMasterDelete)
router.post("/HMS_BillHeaderInsert", dataController.HMS_BillHeaderInsert)
router.post("/HMS_BillHeaderUpdate", dataController.HMS_BillHeaderUpdate)
router.post("/HMS_BillHeaderDelete", dataController.HMS_BillHeaderDelete)
router.post("/HMS_BillDetailsInsert", dataController.HMS_BillDetailsInsert)
router.post("/HMS_BillDetailsUpdate", dataController.HMS_BillDetailsUpdate)
router.post("/HMS_BillDetailsDelete", dataController.HMS_BillDetailsDelete)
router.post("/ServiceSearchCreteria", dataController.ServiceSearchCreteria)
router.post("/getBillingHeader", dataController.getBillingHeader)
router.post("/getBillingDetail", dataController.getBillingDetail)
router.post("/getBillingGetData", dataController.getBillingGetData)
router.post("/BillHdrSearchCreteria", dataController.BillHdrSearchCreteria)
router.post("/PaymentModeInsert", dataController.HMS_PaymentModeInsert)
router.post("/PaymentModeUpdate", dataController.HMS_PaymentModeUpdate)
router.post("/PaymentModeDelete", dataController.HMS_PaymentModeDelete)
router.post("/ServiceInsert", dataController.HMS_ServiceInsert)
router.post("/ServiceUpdate", dataController.HMS_ServiceUpdate)
router.post("/ServiceDelete", dataController.HMS_ServiceDelete)
router.post("/PatientSearchCreteria", dataController.PatientSearchCreteria)
router.post("/PaymentModeSearchCreteria", dataController.PaymentModeSearchCreteria)
router.post("/getDoctorSearchdata", dataController.getDoctorSearchdata)
router.post("/DoctorMasterUpdate2", dataController.HMS_DoctorMasterUpdate2)
router.post("/getClientSearchdata", dataController.getClientSearchdata)
router.post("/ClientMasterUpdate2", dataController.HMS_ClientMasterUpdate2)
router.post("/getPatientName", dataController.getPatientName)
router.post("/getClientName", dataController.getClientName)
router.post("/getDoctorName", dataController.getDoctorName)
router.post("/getServiceDetail", dataController.getServiceDetail)
router.post("/PatientSearchUpdate2", dataController.PatientSearchUpdate2)
router.post("/TotalPatients", dataController.TotalPatients)
router.post("/TotalDiscount", dataController.TotalDiscount)
router.post("/TotalIncome", dataController.TotalIncome)
router.post("/NumberofPatients", dataController.NumberofPatients)
router.post("/NumberofService", dataController.NumberofService)
router.post("/TotalGender", dataController.TotalGender) 
router.post("/updateServiceGrid", dataController.updateServiceGrid) 
router.post("/deleteServiceGrid", dataController.deleteServiceGrid) 
router.post("/getWeeks", dataController.getWeeks) 
router.post("/getDays", dataController.getDays) 
router.post("/getMaritalStatus", dataController.getMaritalStatus) 
router.post("/ANC_Mothers_ScanInsert", dataController.ANC_Mothers_ScanInsert) 
router.post("/GetSearchANC", dataController.GetSearchANC)
router.post("/ANC_Baby_ScanLoopUpdate", dataController.ANC_Baby_ScanLoopUpdate)
router.post("/ANC_Baby_ScanLoopDelete", dataController.ANC_Baby_ScanLoopDelete)
router.post("/ANC_Mother_ScanUpdate", dataController.ANC_Mother_ScanUpdate)
router.post("/GetExcelMother_Scan", dataController.GetExcelMother_Scan)
router.post("/getTransactionType", dataController.getTransactionType)
router.post("/GetBillingReport", dataController.GetBillingReport)
router.post("/GetGenderReport", dataController.GetGenderReport)
router.post("/GetServiceReport", dataController.GetServiceReport)
router.post("/GetServiceName", dataController.GetServiceName)
router.post("/getDoctorDropdown", dataController.getDoctorDropdown)
router.post("/getUserPermission", dataController.getUserPermission)
router.post("/adduserscreenmap", dataController.adduserscreenmap)
router.post("/getAlluserscreenmap", dataController.getAlluserscreenmap)
router.post("/saveEditeduserscreenmap", dataController.saveEditeduserscreenmap)
router.post("/userscreenmapdeleteData", dataController.userscreenmapdeleteData)
router.post("/getuserscreensearchdata", dataController.getuserscreensearchdata)
router.post("/updateRoleRights", dataController.updateRoleRights)
router.post("/getDefaultScreens",dataController.getDefaultScreens)
router.post("/userSettingsInsert",dataController.userSettingsInsert)
router.post("/getUserSettings",dataController.getUserSettings)
router.post("/getDefaultUserCompany",dataController.getDefaultUserCompany)


module.exports = router;